spring.application.name=PatientService

#run this using
# do build : mvn clean install
#run for local if not using docker : SPRING_PROFILES_ACTIVE=local mvn spring-boot:run

spring.profiles.active=local


server.port =9095


#Jpa hibernated related config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#hikari connection pool related config
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

